// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYVvhbgeSH45YbqaNqptArkWfB1SibVoE', // The API key you found
    appId: '1:1074177176657:android:cca1715a91e190a33ff470', // The app ID from the json
    messagingSenderId: '1074177176657', // Use the project number as sender ID
    projectId: 'todo-list-bad74', // The project ID
    storageBucket: 'todo-list-bad74.firebasestorage.app', // The storage bucket
  );


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhn7hmcbJ2tNY8Zk7QCRXwf4cmQ18OEKk', // Your API key
    appId: '1:1074177176657:web:5da8a18f994410013ff470', // Your app ID
    messagingSenderId: '1074177176657', // Your sender ID
    projectId: 'todo-list-bad74', // Your project ID
    authDomain: 'todo-list-bad74.firebaseapp.com', // Your auth domain
    storageBucket: 'todo-list-bad74.firebasestorage.app', // Your storage bucket
    measurementId: 'G-VM5K3KNK1E', // Your measurement ID (for Analytics)
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_IOS_MESSAGING_SENDER_ID',
    projectId: 'todo-list-bad74',
    storageBucket: 'todo-list-bad74.appspot.com',
    iosBundleId: 'com.example.myriam1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9iVn-6Ph5fLkQ2_5e3trgE67Spmri9jY',
    appId: '1:727830725517:ios:6f0305078332755a9b33c4',
    messagingSenderId: '727830725517',
    projectId: 'todolist-10ef1',
    storageBucket: 'todolist-10ef1.appspot.com',
    iosBundleId: 'com.example.myriam1',
  );
}
